# Generated by Django 4.1.1 on 2022-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=40)),
                ('tanggal_lahir', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('fakultas', models.CharField(max_length=40)),
                ('prodi', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
