# Generated by Django 4.1.1 on 2022-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=40)),
                ('tanggal_lahir', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('fakultas', models.CharField(max_length=40)),
                ('prodi', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=40)),
                ('tanggal_lahir', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dosen',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
